
services:
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile  # 使用自定义的 Dockerfile 来构建 PHP 镜像
    image: php:8.0-fpm
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./code:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app_network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: homework
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

